apiVersion: apps/v1
kind: Deployment
metadata:
  name: chambers-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: chambers
  template:
    metadata:
      labels:
        app: chambers
    spec:
      containers:
        - name: chambers
          image: us.gcr.io/nuit-isen/chambers
          env:
            - name: MONGO_URI
              value: "mongodb://chambers-mongo-service:27017/chambers"
---
apiVersion: v1
kind: Service
metadata:
  name: chambers-service
spec:
  selector:
    app: chambers
  ports:
    - name: chambers
      protocol: TCP
      port: 4011
      targetPort: 4011
